[package]
name = "wasmtime-jni"
version = "0.1.0"
authors = ["Yuto Kawamura <kawamuray.dadada@gmail.com>"]
edition = "2018"

[lib]
crate_type = ["cdylib"]

[dependencies]
jni = "0.19.0"
thiserror = "1.0.30"
anyhow = "1.0.56"
wasmtime = "1.0.0"
wasmtime-wasi = "1.0.0"
wasi-common = "1.0.0"
wasi-cap-std-sync = "1.0.0"
cap-std = "0.25.3"
